module.exports = {
    '02':'Alexandria',
    '28':'Aswan',
    '25':'Asyut',
    '18':'Beheira',
    '22':'Beni Suef',
    '01':'Cairo',
    '12':'Dakahlia',
    '11':'Damietta',
    '23':'Faiyum',
    '16':'Gharbia',
    '21':'Giza',
    '19':'Ismailia',
    '15':'Kafr El Sheikh',
    '29':'Luxor',
    '33':'Matruh',
    '24':'Minya',
    '17':'Monufia',
    '32':'New Valley',
    '34':'North Sinai',
    '03':'Port Said',
    '14':'Qalyubia',
    '27':'Qena',
    '31':'Red Sea',
    '13':'Sharqia',
    '26':'Sohag',
    '35':'South Sinai',
    '04':'Suez',
    '88':'Outside Egypt',
}